name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        dotnet restore /NSharp.Compiler
        dotnet restore /NSharp.Core
        dotnet restore /NSharp.Language.Min
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        file: nsc.zip
        target: /lib/nsc.zip
    - name: Unzip
      run: unzip /lib/nsc.zip -d /lib
    - name: Transpile
      run: dotnet /lib/nsc.dll -compile /NSharp.Compiler /NSharp.Core /NSharp.Language.Min
    - name: Build
      run: dotnet build /NSharp.Compiler --no-restore
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
